"""Generate/check five independent Chapter 1 stereo mathematical cue WAVs.

Run with ``python -m codes.chapters.ch01.examples.generate_binaural_cues``.
``--check`` compares source hashes, exact file set, regenerated bytes, actual
PCM and manifest values without creating directories or writing files.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path
import platform
import sys
import wave

import numpy as np

from codes.chapters.ch01.core.binaural_cues import (
    CASES, OUTPUT_SAMPLES, SAMPLE_RATE, build_cues, measure_cues,
)
from codes.chapters.ch00.core.audio_samples import pcm16_bytes, read_pcm16

from codes.chapters.ch00.io_contracts import (
    validate_asset_directory as _shared_asset_directory, strict_json_loads, same_metadata,
)

ROOT = Path(__file__).resolve().parents[4]
DEFAULT_DIRECTORY = ROOT / "codes/chapters/ch01/binaural_audio"
SOURCE_PATHS = (
    'codes/chapters/ch01/core/binaural_cues.py',
    'codes/chapters/ch01/examples/generate_binaural_cues.py',
    'codes/chapters/ch00/core/audio_samples.py',
    'codes/chapters/ch00/io_contracts.py',
)


def wav_metadata(payload: bytes) -> dict:
    """Header inspection, with sample decoding delegated to the shared codec."""
    with wave.open(io.BytesIO(payload), "rb") as wav:
        return {"sample_rate_hz": wav.getframerate(), "channels": wav.getnchannels(),
                "samples_per_channel": wav.getnframes(), "sample_width_bytes": wav.getsampwidth(),
                "compression": wav.getcomptype()}


def expected_assets() -> tuple[dict[str, bytes], dict]:
    """In-memory reconstruction: strict check never repairs published assets."""
    manifest = {
        "schema_version": 1, "exercise_id": "E01-08", "sample_rate_hz": SAMPLE_RATE,
        "common_export_gain": 1., "channel_order": ["left", "right"],
        "source_sha256": {path: hashlib.sha256((ROOT / path).read_bytes()).hexdigest()
                          for path in SOURCE_PATHS},
        "environment": {"python": platform.python_version(), "numpy": np.__version__,
                        "byteorder": sys.byteorder, "platform": platform.platform()},
        "parameters": {"source_samples": 32000, "output_samples": OUTPUT_SAMPLES,
                       "source_duration_s": 2., "output_duration_s": OUTPUT_SAMPLES / SAMPLE_RATE,
                       "frequencies_hz": [500, 800, 1300, 2400], "amplitudes": [.08] * 4,
                       "edge_fade_s": .02, "fade": "linear min(1,t/0.02,(2-t)/0.02)",
                       "seed": None, "initial_history": "zero; causal delay, no circular wrap",
                       "tail": "eight zero-padded frames retain every delayed source sample"},
        "conventions": {"itd": "left arrival minus right arrival; positive means left later",
                        "ild": "10*log10(right mean square / left mean square)",
                        "power": "uncentered digital mean square on equal source support",
                        "correlation": "sum(left[n+lag]*right[n])/sqrt(sum(left^2)*sum(right^2)); fixed N=28800"},
        "quantization": {"format": "signed little-endian PCM16", "scale": 32768,
                         "rounding": "nearest, ties to even", "sample_width_bytes": 2,
                         "max_rounding_error_bound": .5 / 32768, "clipping": "rejected"},
        "limits": "Synthetic stereo delay/gain demonstrations; no HRTF, head diffraction, room, noise, "
                  "physical direction truth or human discrimination experiment. Headphone image cannot establish an angle.",
        "listening": "Start with low playback volume; never autoplay.",
        "files": {}, "samples": {},
    }
    payloads = {}
    for name, signal in build_cues().items():
        payload = pcm16_bytes(signal)
        metadata = wav_metadata(payload)
        _, decoded = read_pcm16(payload)
        delays, gains = CASES[name]
        error = float(np.max(np.abs(decoded - signal)))
        if error > .5 / 32768 + 1e-15:
            raise ValueError("PCM quantization exceeds the rounding bound")
        filename = name + ".wav"
        payloads[filename] = payload
        manifest["files"][filename] = {**metadata, "sha256": hashlib.sha256(payload).hexdigest(),
                                       "peak": float(np.max(np.abs(decoded))),
                                       "quantization_max_abs_error": error}
        manifest["samples"][name] = {
            "file": filename, "delays_samples_left_right": list(delays),
            "gains_left_right": list(gains), "common_export_gain": 1.,
            "float_measurements": measure_cues(signal, delays),
            "pcm_measurements": measure_cues(decoded, delays),
        }
    return payloads, manifest


def check_assets(directory: Path = DEFAULT_DIRECTORY) -> dict:
    """Strict, read-only, current-environment reconstruction and PCM validation."""
    payloads, expected = expected_assets()
    directory = Path(directory)
    required = set(payloads) | {"MANIFEST.json"}
    _shared_asset_directory(directory, required, check=True)
    actual = {path.name for path in directory.iterdir()}
    if actual != required:
        raise ValueError(f"Asset set differs: missing={sorted(required-actual)}, extra={sorted(actual-required)}")
    published = strict_json_loads((directory / "MANIFEST.json").read_text(encoding="utf-8"))
    if not same_metadata(published, expected):
        raise ValueError("Manifest differs from current sources, environment, parameters or measurements")
    for filename, payload in payloads.items():
        actual_payload = (directory / filename).read_bytes()
        if actual_payload != payload:
            raise ValueError(f"Stale or modified WAV: {filename}")
        metadata = wav_metadata(actual_payload)
        _, decoded = read_pcm16(actual_payload)
        recorded = published["files"][filename]
        if any(metadata[key] != recorded[key] for key in metadata):
            raise ValueError(f"PCM metadata mismatch: {filename}")
        stem = Path(filename).stem
        if measure_cues(decoded, CASES[stem][0]) != published["samples"][stem]["pcm_measurements"]:
            raise ValueError(f"Actual PCM measurement mismatch: {filename}")
    return published


def generate_assets(directory: Path = DEFAULT_DIRECTORY) -> dict:
    """Write only this independent asset set, then reread and validate it."""
    payloads, manifest = expected_assets()
    directory = Path(directory)
    required = set(payloads) | {"MANIFEST.json"}
    _shared_asset_directory(directory, required, check=False)
    directory.mkdir(parents=True, exist_ok=True)
    for filename, payload in payloads.items():
        (directory / filename).write_bytes(payload)
    (directory / "MANIFEST.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    return check_assets(directory)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="strictly read-only verification")
    parser.add_argument("--output", type=Path, default=DEFAULT_DIRECTORY)
    args = parser.parse_args()
    try:
        manifest = check_assets(args.output) if args.check else generate_assets(args.output)
    except (OSError, ValueError, wave.Error) as error:
        parser.exit(1, f"Binaural asset verification failed: {error}\n")
    print(f"{'Checked' if args.check else 'Generated and checked'} {len(manifest['files'])} binaural WAVs")


if __name__ == "__main__":
    main()
